//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manager {
	
	
	public partial class AddDoctor {
		
		protected System.Web.UI.WebControls.TextBox txtFullName;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtAddress;
		
		protected System.Web.UI.WebControls.TextBox txtPostcode;
		
		protected System.Web.UI.WebControls.TextBox txtPhoneNumber;
		
		protected System.Web.UI.WebControls.TextBox txtDateofBirth;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.TextBox txtConfirmPassword;
		
		protected System.Web.UI.WebControls.TextBox txtCreationDate;
		
		protected System.Web.UI.WebControls.TextBox txtRegistrationApprovalDate;
		
		protected System.Web.UI.WebControls.CheckBox checkboxApproved;
		
		protected System.Web.UI.WebControls.Button btnAddDoctor;
	}
}
