//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Counselor {
	
	
	public partial class SignUp {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager ScriptManager;
		
		protected System.Web.UI.UpdatePanel UpdatePanel;
		
		protected System.Web.UI.WebControls.TextBox txtFullName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator rf1;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox txtAddress;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox txtPostalcode;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.TextBox txtDateofBirth;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
		
		protected System.Web.UI.WebControls.TextBox txtPhoneNumber;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator5;
		
		protected System.Web.UI.WebControls.TextBox txtPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator6;
		
		protected System.Web.UI.WebControls.TextBox txtConfirmPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator7;
		
		protected System.Web.UI.WebControls.CompareValidator cv;
		
		protected System.Web.UI.WebControls.Label lblFeedback;
		
		protected System.Web.UI.WebControls.Button btnSignup;
	}
}
